### ISSUE TITLE
HACS install - not able to find integration "Temperature Feels Like"

### ISSUE THREAD

**Issue by garithd** [Limych/ha-apparent-temperature#11]
I have HACS 1.12.3 and Home Assistant 2021.4.6 though unable to find "Temperature Feels Like" in HACS "Integrations".
Does work well with manual install 👍 

![Screenshot 2021-05-03 at 08 51 01](https://user-images.githubusercontent.com/4319212/116848348-b4453c80-abec-11eb-8eec-eeb70db52ca0.png)
![Screenshot 2021-05-03 at 08 50 29](https://user-images.githubusercontent.com/4319212/116848326-a4c5f380-abec-11eb-8dd0-8fe0a50ea3d4.png)

**Comment by Limych** [comment]
It's normal. Because PR with this repository not approved yet. https://github.com/hacs/default/pull/903
