### ISSUE TITLE
'temperature_feels_like' calls `async_track_state_change`

### ISSUE THREAD

**Issue by razzietheman** [Limych/ha-apparent-temperature#156]
### System Health details

...

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-temperature-feels-like/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

Detected that custom integration 'temperature_feels_like' calls `async_track_state_change` instead of `async_track_state_change_event` which is deprecated and will be removed in Home Assistant 2025.5 at custom_components/temperature_feels_like/sensor.py, line 200: async_track_state_change(self.hass, list(entities), sensor_state_listener), please create a bug report at https://github.com/Limych/ha-temperature-feeling/issues

### Reproduction steps

1. restarted home assistant
2.
3.
...

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by tjorim** [comment]
Details can be found on the developer blog here: https://developers.home-assistant.io/blog/2024/04/13/deprecate_async_track_state_change

**Comment by Limych** [comment]
Already fixed
