### ISSUE TITLE
it shows feels temp like 8.281

### ISSUE THREAD

**Issue by razzietheman** [Limych/ha-apparent-temperature#162]
### System Health details

.

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-apparent-temperature/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

fron version 1.0.0 it shows feels temp like 8.281 instead of 8,2 or so

### Reproduction steps

1. remove and reinstall
2. restart HA
3.
...

### Debug logs

```text
.
```

### Diagnostics dump

.

**Comment by Limych** [comment]
It's not a bug.

**Comment by razzietheman** [comment]
> It's not a bug.

how to get it to show only 1 decimal in clock weather card?

**Comment by Limych** [comment]
@razzietheman,
Update the component to version 1.1.0, set `unique_id` for the entity, then through the UI in the entity settings set the desired value.
