### ISSUE TITLE
update from 0.4 to 1.0 / 1.1

### ISSUE THREAD

**Issue by razzietheman** [Limych/ha-apparent-temperature#167]
## System Information

version | core-2024.8.0
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.12.4
os_name | Linux
os_version | 6.6.44-haos
arch | x86_64
timezone | Europe/Stockholm
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4838
Installed Version | 1.34.0
Stage | running
Available Repositories | 1390
Downloaded Repositories | 14
HACS Data | ok

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 13.0.rc2
-- | --
update_channel | beta
supervisor_version | supervisor-2024.08.0
agent_version | 1.6.0
docker_version | 26.1.4
disk_total | 228.5 GB
disk_used | 13.9 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Duck DNS (1.18.0), MariaDB (2.7.1), Samba share (12.3.2), phpMyAdmin (0.9.1), Home Assistant Google Drive Backup (0.112.1), Dnsmasq (1.8.1), Mosquitto broker (6.4.1), PS5 MQTT (1.4.0), Piper (1.5.2), Whisper (2.1.2), openWakeWord (1.10.0), Advanced SSH & Web Terminal (18.0.0), Tailscale with features (0.20.0.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 1
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 31 juli 2024 kl. 04:57
-- | --
current_recorder_run | 10 augusti 2024 kl. 07:32
estimated_db_size | 427.39 MiB
database_engine | mysql
database_version | 10.11.6

</details>

<details><summary>Svensk Postutdelning</summary>

Version | 1.0.7
-- | --
Idle | false
Instances | 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/Limych/ha-apparent-temperature/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

update from v 0.4 to 1.0 or 1.1 and in cloeck weather card the version 0.4 shows feels like 10.2 but when update to later versions it starts show 10.246934 or so , try to update from hacs or from this homepage but still getting the same problem , but as soon I put in 0.4 again everything is good.... 

### Reproduction steps

1. update from hacs
2. restart HA
3. remove everything in custom_components and download 0.4 again from homepage
restart HA and it shows correct again
![Skärmbild 2024-08-10 072719](https://github.com/user-attachments/assets/f26106b9-4799-4fd3-a587-04c8b6eea320)
![Skärmbild 2024-08-10 073041](https://github.com/user-attachments/assets/1a03185e-4ed9-4385-9aa6-b0a9985591c5)

### Debug logs

```text
.
```

**Comment by Limych** [comment]
#162
