### ISSUE TITLE
Unique IDs for entities

### ISSUE THREAD

**Issue by DellanX** [Limych/ha-apparent-temperature#168]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/Limych/ha-temperature-feels-like/issues?q=is%3Aissue+label%3A%22enhancement%22+).

### Is your feature request related to a problem? Please describe.

I wish I was able to assign settings such as digits of precision, which is a feature available via the UI if the entities had a unique ID.

### Describe the solution you'd like

Home assistant has a Unique ID for each of this integrations entities, so that the entity can be partially managed from Home assistants UI

### Describe alternatives you've considered

NA

### Additional context

Again, mainly just want to be able to have a badge that displays the current apparant temperature, but with only 3 digits.

**Comment by Limych** [comment]
The ability to assign a unique ID has long been available in the settings.
https://github.com/Limych/ha-apparent-temperature#configuration-variables
