### ISSUE TITLE
add support for self defined temperature and humidity sources

### ISSUE THREAD

**Issue by Mearman** [Limych/ha-apparent-temperature#28]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

Inside, I have a template that calculates the "feels-like" from each temperature and humidity sensor on a per room basis, and also takes the average across all rooms.
I'm wondering if you could add the ability to use your own temperature and humidity sensor(s) (obviously the wind factor is removed)

**Describe alternatives you've considered**

**Additional context**

**Comment by Limych** [comment]
This ability already has. Just set properly device class or unit of meaturement for each of sensor.
