### ISSUE TITLE
Multiple Definitions

### ISSUE THREAD

**Issue by M1Sports20** [Limych/ha-apparent-temperature#85]
**Is your feature request related to a problem? Please describe.**

I want to control HVAC in my home according to feels like temperature.  I have multiple thermostats and I was wondering if more than one feels like temperature can be used.  When I try to only the last stays, even if I define different unique ids.

**Describe the solution you'd like**

Ability to have more than one feels like sensor.

**Describe alternatives you've considered**

**Additional context**

**Comment by nkhdk** [comment]
It's already working with multiple sensors.

As inspiration this is my config that gives me four different sensors:

`# Apparent temperature
sensor apparent_temperature:
  - platform: apparent_temperature
    name: 'Bedroom Feels Like Temperature'
    source:
      - sensor.netatmo_kitchen_bedroom_temperature
      - sensor.netatmo_kitchen_bedroom_humidity
  - platform: apparent_temperature
    name: 'Bathroom Feels Like Temperature'
    source:
      - sensor.lumi_lumi_weather_0237e_1_1026
      - sensor.lumi_lumi_weather_0237e_1_1029
  - platform: apparent_temperature
    name: 'Balcony Feels Like Temperature'
    source:
      - sensor.lumi_lumi_weather_balcony_temperature_3
      - sensor.lumi_lumi_weather_balcony_humidity_3
  - platform: apparent_temperature
    name: 'Kitchen Feels Like Temperature'
    source:
      - sensor.netatmo_kitchen_temperature
      - sensor.netatmo_kitchen_humidity`
