### ISSUE TITLE
breaking stuf soon

### ISSUE THREAD

**Issue by Tntdruid** [Limych/ha-apparent-temperature#96]
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for temperature_feels_like using this method at custom_components/temperature_feels_like/sensor.py, line 247: temperature = convert_temperature(
Detected integration that uses temperature utility. This is deprecated since 2022.10 and will stop working in Home Assistant 2022.4, it should be updated to use unit_conversion.TemperatureConverter instead. Please report issue to the custom integration author for temperature_feels_like using this method at custom_components/temperature_feels_like/sensor.py, line 329: convert_temperature(feeling, TEMP_CELSIUS, self.unit_of_measurement), 1

**Comment by Limych** [comment]
see #93
